server:
  port: 8869
  servlet:
    context-path: /ltree
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/xfc_ltree
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
mybatis-plus:
  type-aliases-package: com.xfc.ltree.entities
  mapper-locations:classpath*: mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl